org.gradle.jvmargs=-Xmx2G
org.gradle.workers.max=5
org.gradle.parallel=true

mod.group=com.bawnorton
mod.id=configurable
mod.name=Configurable
mod.version=3.4.0
mod.author=Bawnorton
mod.license=MIT
mod.description=Config library that allows decentralised settings in a mod

publishing.curseforge=1092048
publishing.modrinth=lGffrQ3O
