modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/Bawnorton/${mod_name}/issues"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "Bawnorton"
description = '''
${description}
'''
logoFile = "assets/${mod_id}/icon.png"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}-client.mixins.json"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side = "BOTH"